DROP DATABASE IF EXISTS DND;

CREATE DATABASE IF NOT EXISTS DND;
USE DND;

CREATE TABLE Personajes(
id INT PRIMARY KEY AUTO_INCREMENT,
nombre VARCHAR(40) NOT NULL,
nivel INT NOT NULL,
clase VARCHAR(20) NOT NULL,
id_campaña INT Not NULL);

CREATE TABLE partidas(
id INT PRIMARY KEY AUTO_INCREMENT,
nombre VARCHAR(50) NOT NULL,
dificultad VARCHAR(25) NOT NULL);

ALTER TABLE Personajes
ADD CONSTRAINT Personajes_Partidas FOREIGN KEY (id_campaña)
REFERENCES partidas (id)
ON DELETE CASCADE
ON UPDATE CASCADE;

