/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

/**
 *
 * @author a23carlosgg
 */
public class VistaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MenuAddPersonaje = new javax.swing.JMenuItem();
        MenuVerPersonaje = new javax.swing.JMenuItem();
        MenuUpdatePersonaje = new javax.swing.JMenuItem();
        MenuDeletePersonaje = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        MenuAddCampaña = new javax.swing.JMenuItem();
        MenuVerCampaña = new javax.swing.JMenuItem();
        MenuUpdateCampaña = new javax.swing.JMenuItem();
        MenuDeleteCampaña = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 915, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 643, Short.MAX_VALUE)
        );

        jMenu1.setText("Personajes");
        jMenu1.setToolTipText("Despliega el menú de perrsonajes");

        MenuAddPersonaje.setText("Añadir personaje");
        jMenu1.add(MenuAddPersonaje);

        MenuVerPersonaje.setText("Ver personajes creados");
        jMenu1.add(MenuVerPersonaje);

        MenuUpdatePersonaje.setText("Actualizar personaje");
        jMenu1.add(MenuUpdatePersonaje);

        MenuDeletePersonaje.setText("Eliminar personaje");
        jMenu1.add(MenuDeletePersonaje);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Campañas");
        jMenu2.setToolTipText("Despliega el menú de campañas");

        MenuAddCampaña.setText("Añadir campaña");
        jMenu2.add(MenuAddCampaña);

        MenuVerCampaña.setText("Ver campañas existentes");
        jMenu2.add(MenuVerCampaña);

        MenuUpdateCampaña.setText("Actualizar campaña");
        jMenu2.add(MenuUpdateCampaña);

        MenuDeleteCampaña.setText("Borrar campaña");
        jMenu2.add(MenuDeleteCampaña);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Más información");
        jMenu3.setToolTipText("Información más en detalle de la aplicacion");
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Ayuda");
        jMenu4.setToolTipText("Ayuda sobre la aplicación");
        jMenuBar1.add(jMenu4);

        jMenu5.setText("Salir");
        jMenu5.setToolTipText("Salir de la aplicación");
        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuAddCampaña;
    private javax.swing.JMenuItem MenuAddPersonaje;
    private javax.swing.JMenuItem MenuDeleteCampaña;
    private javax.swing.JMenuItem MenuDeletePersonaje;
    private javax.swing.JMenuItem MenuUpdateCampaña;
    private javax.swing.JMenuItem MenuUpdatePersonaje;
    private javax.swing.JMenuItem MenuVerCampaña;
    private javax.swing.JMenuItem MenuVerPersonaje;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
