/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;

import Controlador.CampanaController;
import Modelo.ModeloCampana;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author carlo
 */
public class ActualizarCampaña extends javax.swing.JInternalFrame {

    /**
     * Creates new form CrearPersonaje
     */
    private CampanaController controlador = new CampanaController();

    public ActualizarCampaña(String nombre) throws SQLException {
        initComponents();
        grupoDificultad = new javax.swing.ButtonGroup();
        grupoDificultad.add(botonFacil);
        grupoDificultad.add(botonNormal);
        grupoDificultad.add(botonDificil);
        grupoDificultad.add(botonMuyDificil);

        cargarDatosDesdeController(nombre);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        textoNombreViejo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        textoNuevoNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        botonFacil = new javax.swing.JRadioButton();
        botonNormal = new javax.swing.JRadioButton();
        botonDificil = new javax.swing.JRadioButton();
        botonMuyDificil = new javax.swing.JRadioButton();
        botonUpdate = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();

        jLabel1.setText("Introduzca el nombre de la campaña:");

        jLabel2.setText("Nuevo nombre (opcional):");

        jLabel3.setText("Nueva dificultad:");

        botonFacil.setText("Fácil");

        botonNormal.setText("Medio");

        botonDificil.setText("Difícil");

        botonMuyDificil.setText("Muy difícil");

        botonUpdate.setText("Actualizar información");
        botonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonUpdateActionPerformed(evt);
            }
        });

        botonSalir.setText("Salir");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textoNombreViejo, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(textoNuevoNombre))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(botonFacil)
                            .addComponent(botonNormal)
                            .addComponent(botonDificil)
                            .addComponent(botonMuyDificil))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonSalir)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textoNombreViejo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textoNuevoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(botonFacil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonNormal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonDificil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonMuyDificil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonUpdate)
                    .addComponent(botonSalir))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonUpdateActionPerformed
        String nombreViejo = textoNombreViejo.getText();
    String nuevoNombre = textoNuevoNombre.getText().isEmpty() ? nombreViejo : textoNuevoNombre.getText();

    String nuevaDificultad = null;
    if (botonFacil.isSelected()) nuevaDificultad = "fácil";
    else if (botonNormal.isSelected()) nuevaDificultad = "medio";
    else if (botonDificil.isSelected()) nuevaDificultad = "difícil";
    else if (botonMuyDificil.isSelected()) nuevaDificultad = "muy difícil";

    if (nuevaDificultad == null) {
        JOptionPane.showMessageDialog(this, "Selecciona una dificultad.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        return;
    }

    try {
        ModeloCampana campaña = new ModeloCampana();
        campaña.setNombre(nuevoNombre);
        campaña.setDificultad(nuevaDificultad);

        controlador.actualizarCampaña(nombreViejo, campaña); // implementas esto en el controlador

        JOptionPane.showMessageDialog(this, "Campaña actualizada correctamente.");
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Error al actualizar campaña.", "Error", JOptionPane.ERROR_MESSAGE);
        ex.printStackTrace();
    }
}

private void cargarDatosDesdeController(String nombre) {
        try {
            ModeloCampana campaña = controlador.obtenerCampañaPorNombre(nombre);
            if (campaña != null) {
                textoNombreViejo.setText(campaña.getNombre());
                textoNombreViejo.setEditable(false); // No editable ya que es clave

                switch (campaña.getDificultad().toLowerCase()) {
                    case "fácil":
                        botonFacil.setSelected(true);
                        break;
                    case "medio":
                        botonNormal.setSelected(true);
                        break;
                    case "difícil":
                        botonDificil.setSelected(true);
                        break;
                    case "muy difícil":
                        botonMuyDificil.setSelected(true);
                        break;
                }

            } else {
                JOptionPane.showMessageDialog(this, "Campaña no encontrada", "Aviso", JOptionPane.WARNING_MESSAGE);
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al cargar campaña", "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }
    }//GEN-LAST:event_botonUpdateActionPerformed

private javax.swing.ButtonGroup grupoDificultad;


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton botonDificil;
    private javax.swing.JRadioButton botonFacil;
    private javax.swing.JRadioButton botonMuyDificil;
    private javax.swing.JRadioButton botonNormal;
    private javax.swing.JButton botonSalir;
    private javax.swing.JButton botonUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField textoNombreViejo;
    private javax.swing.JTextField textoNuevoNombre;
    // End of variables declaration//GEN-END:variables
