/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;

import Controlador.PersonajeController;
import Modelo.ModeloCampana;
import Modelo.ModeloPersonaje;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author carlo
 */
public class ActualizarPersonaje extends javax.swing.JInternalFrame {

    /**
     * Creates new form CrearPersonaje
     */
    private Map<String, Integer> mapaCampanas = new HashMap<>();
    PersonajeController controlador;

    public ActualizarPersonaje(String nombre) throws SQLException {
        controlador = new PersonajeController();
        initComponents();
        cargarDatosDesdeController(nombre);
        cargarCampanas();
    }

    private void cargarDatosDesdeController(String nombre) {
        try {
            ModeloPersonaje personaje = controlador.obtenerPersonajePorNombre(nombre);
            if (personaje != null) {
                textoNombreViejo.setText(personaje.getNombrePersonaje());
                textoNombreViejo.setEditable(false);

                comboNiveles.setSelectedItem(String.valueOf(personaje.getNivel()));

                listaClase.setSelectedValue(personaje.getClase(), true);

                for (int i = 0; i < listaCampanas.getModel().getSize(); i++) {
                    String item = listaCampanas.getModel().getElementAt(i);
                    if (item.startsWith(personaje.getId_campana() + " -")) {
                        listaCampanas.setSelectedIndex(i);
                        break;
                    }
                }
            } else {
                JOptionPane.showMessageDialog(this, "Personaje no encontrado", "Aviso", JOptionPane.WARNING_MESSAGE);
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al cargar personaje", "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }

    private void cargarCampanas() {
    DefaultListModel<String> modelo = new DefaultListModel<>();
    mapaCampanas.clear();
     try {
        Modelo.ConnectionBD conexionBD = new Modelo.ConnectionBD();
        conexionBD.connection();

        String sql = "SELECT id, nombre FROM partidas";
        ResultSet rs = conexionBD.getStatement().executeQuery(sql);

        while (rs.next()) {
            int id = rs.getInt("id");
            String nombre = rs.getString("nombre");

            modelo.addElement(nombre);                // Añade el nombre al modelo del JList
            mapaCampanas.put(nombre, id);             // Guarda el par nombre -> id
        }

        listaCampanas.setModel(modelo); // Asigna el modelo con los nombres al JList

        rs.close();
        conexionBD.closeConnection();

    } catch (SQLException ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error al cargar campañas: " + ex.getMessage());
    }
}
            /**
             * This method is called from within the constructor to initialize
             * the form. WARNING: Do NOT modify this code. The content of this
             * method is always regenerated by the Form Editor.
             */
            @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        textoNombreViejo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        textoNombreNuevo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        comboNiveles = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        listaClases = new javax.swing.JScrollPane();
        listaClase = new javax.swing.JList<>();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaCampanas = new javax.swing.JList<>();
        botonUpdate = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();

        jLabel1.setText("Introduce el nombre del personaje:");

        jLabel2.setText("Nuevo nombre(poner el mismo si no se cambia:");

        jLabel3.setText("Nivel:");

        comboNiveles.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20" }));

        jLabel4.setText("Clase:");

        listaClase.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Artificiero", "Bárbaro", "Bardo", "Clérigo", "Druida", "Luchador", "Paladin", "Mago", "Brujo", "Hechicero", "Guardabosques" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listaClases.setViewportView(listaClase);

        jLabel5.setText("Campaña");

        jScrollPane2.setViewportView(listaCampanas);

        botonUpdate.setText("Actualizar información");
        botonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonUpdateActionPerformed(evt);
            }
        });

        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(textoNombreViejo, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(textoNombreNuevo))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(comboNiveles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(listaClases, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonSalir)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textoNombreViejo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textoNombreNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(comboNiveles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(listaClases, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonUpdate)
                    .addComponent(botonSalir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_botonSalirActionPerformed

    private void botonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonUpdateActionPerformed
        String nombreViejo = textoNombreViejo.getText();
        String nuevoNombre = textoNombreNuevo.getText().isEmpty() ? nombreViejo : textoNombreNuevo.getText();
        String clase = listaClase.getSelectedValue();
        int nivel = Integer.parseInt(comboNiveles.getSelectedItem().toString());

        String nombreCampaña = listaCampanas.getSelectedValue(); // Solo nombre visible
        int idCampaña = -1;
        try {
            idCampaña = controlador.obtenerIdCampañaPorNombre(nombreCampaña); // AQUÍ USAS EL MÉTODO
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "No se pudo obtener el ID de la campaña", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            ModeloPersonaje personaje = new ModeloPersonaje();
            personaje.setNombrePersonaje(nuevoNombre);
            personaje.setClase(clase);
            personaje.setNivel(nivel);
            personaje.setId_campana(idCampaña);

            controlador.actualizarPersonaje(nombreViejo, personaje);

            JOptionPane.showMessageDialog(null, "Personaje actualizado correctamente.");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error al actualizar personaje.", "Error", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_botonUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonSalir;
    private javax.swing.JButton botonUpdate;
    private javax.swing.JComboBox<String> comboNiveles;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> listaCampanas;
    private javax.swing.JList<String> listaClase;
    private javax.swing.JScrollPane listaClases;
    private javax.swing.JTextField textoNombreNuevo;
    private javax.swing.JTextField textoNombreViejo;
    // End of variables declaration//GEN-END:variables
}
