/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;

import Controlador.CampanaController;
import Modelo.ModeloCampana;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author carlo
 */
public class CrearCampana extends javax.swing.JInternalFrame {

    CampanaController controlador;
    
    public CrearCampana() throws SQLException {
        this.controlador = new CampanaController();
        initComponents();
        botonFacil.setActionCommand("Fácil");
        botonNormal.setActionCommand("Media");
        botonDificil.setActionCommand("Difícil");
        botonMuyDificil.setActionCommand("Muy difícil");
    }

/**
     * Creates new form CrearPersonaje
     */
        /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoDificultad = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        textoNombre = new javax.swing.JTextField();
        botonFacil = new javax.swing.JRadioButton();
        botonNormal = new javax.swing.JRadioButton();
        botonDificil = new javax.swing.JRadioButton();
        botonMuyDificil = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        botonAdd = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();

        jLabel1.setText("Nombre:");

        grupoDificultad.add(botonFacil);
        botonFacil.setText("Facil");
        botonFacil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonFacilActionPerformed(evt);
            }
        });

        grupoDificultad.add(botonNormal);
        botonNormal.setText("Normal");

        grupoDificultad.add(botonDificil);
        botonDificil.setText("Difícil");

        grupoDificultad.add(botonMuyDificil);
        botonMuyDificil.setText("Muy Difícil");

        jLabel2.setText("Seleccione aquí la dificultad de la campaña");

        botonAdd.setText("Añadir");
        botonAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonAddMouseClicked(evt);
            }
        });

        botonSalir.setText("Salir");
        botonSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonSalirMouseClicked(evt);
            }
        });
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(textoNombre))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(botonFacil)
                            .addComponent(botonNormal)
                            .addComponent(botonDificil)
                            .addComponent(botonMuyDificil)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonSalir)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(botonFacil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonNormal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonDificil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonMuyDificil)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAdd)
                    .addComponent(botonSalir))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonFacilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonFacilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonFacilActionPerformed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonSalirActionPerformed

    private void botonSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonSalirMouseClicked
        this.dispose();
    }//GEN-LAST:event_botonSalirMouseClicked

    private void botonAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAddMouseClicked
        if (!textoNombre.getText().isEmpty() && grupoDificultad.getSelection() != null){
            String nombre = textoNombre.getText();
            String dificultad = grupoDificultad.getSelection().getActionCommand();
            ModeloCampana campana = new ModeloCampana(nombre, dificultad); 
            try {
                controlador.crearCampana(campana);
                JOptionPane.showMessageDialog(null, "Campaña añadida en la base de datos");
            } catch (SQLException ex) {
                Logger.getLogger(CrearCampana.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else JOptionPane.showMessageDialog(null, "Por favor rellene los campos ", title, HEIGHT);
        
    }//GEN-LAST:event_botonAddMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAdd;
    private javax.swing.JRadioButton botonDificil;
    private javax.swing.JRadioButton botonFacil;
    private javax.swing.JRadioButton botonMuyDificil;
    private javax.swing.JRadioButton botonNormal;
    private javax.swing.JButton botonSalir;
    private javax.swing.ButtonGroup grupoDificultad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField textoNombre;
    // End of variables declaration//GEN-END:variables
}
