/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import Vistas.VerCampana;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDesktopPane;

/**
 *
 * @author carlo
 */
public class VistaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {
        initComponents();
    }

    public JDesktopPane getjDesktopPane1() {
        return jDesktopPane1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MenuCrearP = new javax.swing.JMenuItem();
        MenuUpdateP = new javax.swing.JMenuItem();
        MenuDeleteP = new javax.swing.JMenuItem();
        MenuVerP = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        MenuCrearC = new javax.swing.JMenuItem();
        MenuUpdateC = new javax.swing.JMenuItem();
        MenuDeleteC = new javax.swing.JMenuItem();
        MenuVerC = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 598, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 727, Short.MAX_VALUE)
        );

        jMenu1.setText("Personajes");

        MenuCrearP.setText("Crear personaje");
        MenuCrearP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCrearPActionPerformed(evt);
            }
        });
        jMenu1.add(MenuCrearP);

        MenuUpdateP.setText("Actualizar datos de personaje");
        jMenu1.add(MenuUpdateP);

        MenuDeleteP.setText("Eliminar personaje");
        MenuDeleteP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuDeletePActionPerformed(evt);
            }
        });
        jMenu1.add(MenuDeleteP);

        MenuVerP.setText("Ver personajes");
        MenuVerP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuVerPActionPerformed(evt);
            }
        });
        jMenu1.add(MenuVerP);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Campaña");

        MenuCrearC.setText("Crear Campaña");
        MenuCrearC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuCrearCMouseClicked(evt);
            }
        });
        MenuCrearC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCrearCActionPerformed(evt);
            }
        });
        jMenu2.add(MenuCrearC);

        MenuUpdateC.setText("Actualizar datos de Campaña");
        MenuUpdateC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuUpdateCActionPerformed(evt);
            }
        });
        jMenu2.add(MenuUpdateC);

        MenuDeleteC.setText("Eliminar Campaña");
        MenuDeleteC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuDeleteCActionPerformed(evt);
            }
        });
        jMenu2.add(MenuDeleteC);

        MenuVerC.setText("Ver Campañas");
        MenuVerC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuVerCActionPerformed(evt);
            }
        });
        jMenu2.add(MenuVerC);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Más Informacion");
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Ayuda");
        jMenuBar1.add(jMenu4);

        jMenu5.setText("Salir");
        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuCrearPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCrearPActionPerformed
        CrearPersonaje crearP;
        crearP = new CrearPersonaje();
        crearP.setVisible(true);
        jDesktopPane1.add(crearP);
    }//GEN-LAST:event_MenuCrearPActionPerformed

    private void MenuDeleteCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuDeleteCActionPerformed
        BorrarCampana borrarC;
        try {
            borrarC = new BorrarCampana();
            borrarC.setVisible(true);
            jDesktopPane1.add(borrarC);
        } catch (SQLException ex) {
            Logger.getLogger(VistaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_MenuDeleteCActionPerformed

    private void MenuCrearCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCrearCActionPerformed
        CrearCampana crearC;
        try {
            crearC = new CrearCampana();
            crearC.setVisible(true);
            jDesktopPane1.add(crearC);
        } catch (SQLException ex) {
            Logger.getLogger(VistaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_MenuCrearCActionPerformed

    private void MenuCrearCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuCrearCMouseClicked

    }//GEN-LAST:event_MenuCrearCMouseClicked

    private void MenuUpdateCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuUpdateCActionPerformed
        /*ActualizarCampaña updateC;
        try {
            updateC = new ActualizarCampaña();
            updateC.setVisible(true);
            jDesktopPane1.add(updateC);
        } catch (SQLException ex) {
            Logger.getLogger(VistaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }*/    }//GEN-LAST:event_MenuUpdateCActionPerformed

    private void MenuVerCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuVerCActionPerformed
        VerCampana verC;
        try {
            verC = new VerCampana(this);  // <- aquí pasas la instancia
            verC.setVisible(true);
            jDesktopPane1.add(verC);
        } catch (SQLException ex) {
            Logger.getLogger(VistaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }    }//GEN-LAST:event_MenuVerCActionPerformed

    private void MenuDeletePActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuDeletePActionPerformed
        BorrarPersonaje borrarP;
        borrarP = new BorrarPersonaje();
        borrarP.setVisible(true);
        jDesktopPane1.add(borrarP);
    }//GEN-LAST:event_MenuDeletePActionPerformed

    private void MenuVerPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuVerPActionPerformed
        VerPersonajes verP;
        try {
            verP = new VerPersonajes(this);
            verP.setVisible(true);
            jDesktopPane1.add(verP);
        } catch (SQLException ex) {
            Logger.getLogger(VistaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_MenuVerPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuCrearC;
    private javax.swing.JMenuItem MenuCrearP;
    private javax.swing.JMenuItem MenuDeleteC;
    private javax.swing.JMenuItem MenuDeleteP;
    private javax.swing.JMenuItem MenuUpdateC;
    private javax.swing.JMenuItem MenuUpdateP;
    private javax.swing.JMenuItem MenuVerC;
    private javax.swing.JMenuItem MenuVerP;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables

}
